### ISSUE TITLE
Regression:  'rare filter'  now ignores '-e' form of '--extract' flag

### ISSUE THREAD

**Issue by obaudys** [zix99/rare#41]
Before:
![image](https://user-images.githubusercontent.com/53287664/117759749-a2583f00-b267-11eb-9e8b-af503a5e684f.png)

Now:
![image](https://user-images.githubusercontent.com/53287664/117759818-c74cb200-b267-11eb-9426-ae9df54c1641.png)

Now but with `--extract`:
![image](https://user-images.githubusercontent.com/53287664/117759917-f4996000-b267-11eb-867c-57fc8f583369.png)

I've taken screenshots to preserve image highlighting; here's the cut-and-paste friendly test case:
`
echo "a: 1 b: 2 c: 3" | ./rare f -m 'a: (\d+) b: (\d+) c: (\d+)' -e '{1} {2} {3}'
`

Everything seems to work fine using the short '-e' with histogram, analyze, etc;  it's just filter that is impacted.

**Comment by obaudys** [comment]
I've done a git bisect,  and it seems the regression was part of:
[6dbcbc4ebe9f703d9aa1d13d6e04853745b32f95] Multi dimensions via multi arguments (#39)

**Comment by zix99** [comment]
Thanks @obaudys . I took a deeper look, and noticed that `c.IsSet` (in urfave/cli) wasn't working the same way for a `StringFlag` and a `StringSliceFlag` (Which that commit you linked to was switching it to).  The work-around is easy, but I also just tested updating `urfave/cli` from 1.22.2 -> 1.22.5, and that seems to resolve it as well.

Since this is a minor version bump, I'll do a bit more testing, but should release a patch version of rare tonight.
